version: '3.4'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/local.conf:/config/local.conf
      - static:/static
    depends_on:
      - interfaceserver
  interfaceserver:
    build: 
      context: .
      args:
        user_id: 1000
    image: seandooher/ohqueue:${ID:-latest}
    command: /entry/entrypoint-interface.sh
    environment:
      POSTGRES_HOST: "database"
      PROJECT_NAME: "ohqueue"
      DJANGO_DOCKER: "TRUE"
    expose:
      - "8000"
    depends_on:
      - database
      - redis
    volumes:
      - static:/static
  database:
    image: postgres:9.5
  redis:
    image: redis:3.0-alpine
volumes:
   static:
