version: '3.4'
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./ohqueue/frontend/assets/bundles:/static/bundles
  reactserver:
    build:
      context: .
      target: react-pkg
    working_dir: /ohqueue
    command: sh -c "npm install package.json; npm run watch"
    volumes:
      - ./ohqueue/webpack-stats.json:/ohqueue/webpack-stats.json
      - ./ohqueue/:/ohqueue/
  interfaceserver:
    depends_on:
      - reactserver
    volumes:
      - ./ohqueue:/ohqueue
      - ./ohqueue/frontend/assets/bundles:/static/bundles
  database:
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
