version: '3.4'
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./example_project/assets/bundles:/static/bundles
  reactserver:
    build:
      context: .
      target: react-pkg
    working_dir: /example_project
    command: sh -c "npm install package.json; npm run watch"
    volumes:
      - ./example_project/webpack-stats.json:/example_project/webpack-stats.json
      - ./example_project/:/example_project/
  interfaceserver:    
    depends_on:
      - reactserver
    volumes:
      - ./example_project:/example_project
      - ./example_project/frontend/static/assets/bundles:/static/bundles
    env_file:
      - config/local.env
  database:
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
