version: '3.4'
services:
  reactserver:
    build:
      context: .
      target: react-pkg
    working_dir: /ohqueue
    ports: 
      - "3000:3000"
    command: sh -c "npm install package.json; node react_server.js"
    volumes:
      - ./ohqueue/webpack-stats.json:/ohqueue/webpack-stats.json
      - ./ohqueue/:/ohqueue/
  interfaceserver:
    ports:
      - "8000:8000"
    depends_on:
      - reactserver
    volumes:
      - ./ohqueue:/ohqueue
  database:
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
