version: '3.4'
services:
  nginx:
    container_name: PROJECT_NAME-nginx
    env_file:
      - config/production.env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/production.conf:/config/production.conf
      - /docker-volumes/etc/letsencrypt/live/${DJANGO_HOST}/fullchain.pem:/certs/cert.pem
      - /docker-volumes/etc/letsencrypt/live/${DJANGO_HOST}/privkey.pem:/certs/key.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
      - nginx_logs:/logs
    command: /bin/bash -c "envsubst '$$DJANGO_HOSTNAME' < /config/production.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  interfaceserver:
    env_file:
      - config/production.env
  workerserver:
    image: REPO/PROJECT_NAME:${ID:-latest}
    command: /entry/entrypoint-worker.sh
    environment:
      POSTGRES_HOST: "database"
      PROJECT_NAME: "PROJECT_NAME"
      DJANGO_DOCKER: "TRUE"
    env_file:
      - config/production.env
    depends_on:
      - database
      - redis
  database:
    env_file:
      - config/production.env
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  nginx_logs:
