version: '3.4'
services:
  reactserver:
    build:
      context: .
      target: react-pkg
    working_dir: /ohqueue
    volumes:
      - ./reports:/ohqueue/reports
  interfaceserver:
    depends_on:
      - reactserver
    volumes:
      - ./reports:/ohqueue/reports
