info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/events/:
    get:
      description: Lists all TicketEvents (for statistical purposes)
      operationId: events_list
      tags:
      - events
  /api/events/{id}/:
    get:
      description: Lists all TicketEvents (for statistical purposes)
      operationId: events_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket event.
          title: !!python/tuple
          - ID
          type: integer
      tags:
      - events
  /api/myticket/:
    delete:
      description: Marks the users ticket as deleted.
      operationId: myticket_delete
      tags:
      - myticket
    get:
      description: Returns the users current ticket.
      operationId: myticket_read
      tags:
      - myticket
    patch:
      description: Changes certain attributes of the ticket model. Needs one or more
        of all the fields.
      operationId: myticket_partial_update
      tags:
      - myticket
    post:
      description: Creates a new user ticket, deleting the users active ticket if
        it exists. Needs assignment, question, description, and location.
      operationId: myticket_create
      tags:
      - myticket
    put:
      description: Changes certain attributes of the ticket model. Needs all of the
        fields.
      operationId: myticket_update
      tags:
      - myticket
  /api/queue/:
    get:
      description: Lists all tickets currently able to be assigned
      operationId: queue_list
      tags:
      - queue
  /api/queue/{id}/:
    get:
      description: Lists all tickets currently able to be assigned
      operationId: queue_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: !!python/tuple
          - ID
          type: integer
      tags:
      - queue
  /api/tickets/:
    get:
      description: Lists all tickets ever created
      operationId: tickets_list
      tags:
      - tickets
  /api/tickets/{id}/:
    get:
      description: Lists all tickets ever created
      operationId: tickets_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this ticket.
          title: !!python/tuple
          - ID
          type: integer
      tags:
      - tickets
servers:
- url: ''
