# Generated by Django 2.1.4 on 2018-12-18 10:29

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(backend.models.TicketStatus('pending'), 'pending'), (backend.models.TicketStatus('assigned'), 'assigned'), (backend.models.TicketStatus('resolved'), 'resolved'), (backend.models.TicketStatus('deleted'), 'deleted')], db_index=True, max_length=20)),
                ('assignment', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helping', to='backend.Profile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='backend.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[(backend.models.TicketEventType('create'), 'create'), (backend.models.TicketEventType('assign'), 'assign'), (backend.models.TicketEventType('unassign'), 'unassign'), (backend.models.TicketEventType('resolve'), 'resolve'), (backend.models.TicketEventType('delete'), 'delete'), (backend.models.TicketEventType('describe'), 'describe')], db_index=True, max_length=20)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Profile')),
            ],
        ),
    ]
