# Generated by Django 2.1.4 on 2018-12-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('student', 'student'), ('lab_assistant', 'lab_assistant'), ('teaching_assistant', 'teaching_assistant')], db_index=True, default='student', max_length=64),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('resolved', 'resolved'), ('deleted', 'deleted')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='event_type',
            field=models.CharField(choices=[('create', 'create'), ('assign', 'assign'), ('unassign', 'unassign'), ('resolve', 'resolve'), ('delete', 'delete'), ('describe', 'describe')], db_index=True, max_length=20),
        ),
    ]
