# Generated by Django 2.1.4 on 2018-12-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181229_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignment',
            field=models.CharField(help_text='assignment the student is requesting help with', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='description of the problem the student has'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='helper',
            field=models.ForeignKey(help_text='which staff member is currently assisting the student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helping', to='backend.Profile'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.CharField(help_text='location of the student', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='question',
            field=models.CharField(help_text='question on the assignment the student is requesting help with', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('resolved', 'resolved'), ('deleted', 'deleted')], db_index=True, help_text='current status of this ticket', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(help_text='student who opened this ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='backend.Profile'),
        ),
    ]
