# Generated by Django 2.1.4 on 2019-01-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181230_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
